#define WORLD_WIDTH  15
#define WORLD_HEIGHT 14

#define GRASS 0
#define WATER 1
#define TREES 2
#define STONE 3

const unsigned char tiles[] PROGMEM = {
  //width, height,
  16, 16,
  //Grass
  0xff, 0x7f, 0xfb, 0xff, 0xff, 0xbf, 0xff, 0xff, 0xf7, 0xff, 0xfd, 0xff, 0xff, 0xf7, 0x7f, 0xff, 
  0xdf, 0xff, 0xff, 0xfb, 0x7f, 0xff, 0xff, 0xff, 0xef, 0xfe, 0xff, 0xff, 0xfb, 0xff, 0x7f, 0xff, 
  
  //Water
  0x08, 0x10, 0x10, 0x08, 0x10, 0x08, 0x10, 0x10, 0x10, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0x20, 0x40, 0x40, 0x20, 0x00, 0x01, 0x02, 0x02, 0x01, 0x02, 0x02, 0x01, 0x02, 0x21, 0x40, 0x40, 
  
  //Tree
  0xff, 0x1f, 0x5b, 0x3f, 0xeb, 0xdd, 0xff, 0xf7, 0xbb, 0xef, 0xfd, 0x7f, 0xe3, 0xcb, 0xe3, 0xff, 
  0xff, 0xc7, 0x96, 0xc7, 0xff, 0xff, 0xef, 0xfd, 0xff, 0xe3, 0xcb, 0xe3, 0xff, 0xff, 0x7b, 0xff, 
  
  //Stone
  0xff, 0xdf, 0x7b, 0x3f, 0x9f, 0x6f, 0x77, 0xab, 0xdb, 0xd7, 0xcd, 0x5f, 0xbf, 0x77, 0xff, 0xff, 
  0xff, 0xc1, 0xdc, 0xd3, 0xaf, 0x9f, 0xae, 0xb0, 0xbb, 0xbd, 0xbd, 0xba, 0xd7, 0xcc, 0x63, 0xff, 
};

int world[WORLD_HEIGHT][WORLD_WIDTH] = {
  { TREES, GRASS, GRASS, WATER, GRASS, GRASS, GRASS, TREES, GRASS, GRASS, GRASS, GRASS, GRASS, TREES, GRASS },
  { GRASS, WATER, WATER, WATER, GRASS, WATER, GRASS, GRASS, GRASS, GRASS, GRASS, STONE, GRASS, GRASS, GRASS },
  { GRASS, GRASS, GRASS, GRASS, GRASS, WATER, STONE, GRASS, GRASS, GRASS, TREES, GRASS, GRASS, GRASS, GRASS },
  { STONE, GRASS, GRASS, STONE, TREES, WATER, WATER, WATER, GRASS, WATER, WATER, GRASS, TREES, GRASS, GRASS },
  { GRASS, GRASS, GRASS, GRASS, TREES, GRASS, GRASS, GRASS, GRASS, WATER, GRASS, GRASS, STONE, TREES, GRASS },
  { GRASS, GRASS, GRASS, WATER, STONE, GRASS, GRASS, TREES, GRASS, TREES, GRASS, GRASS, WATER, WATER, GRASS },
  { GRASS, WATER, WATER, TREES, GRASS, WATER, WATER, STONE, WATER, GRASS, GRASS, GRASS, GRASS, STONE, GRASS },
  { GRASS, TREES, STONE, TREES, GRASS, WATER, GRASS, TREES, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS },
  { GRASS, TREES, GRASS, STONE, GRASS, GRASS, GRASS, GRASS, GRASS, STONE, GRASS, GRASS, GRASS, GRASS, GRASS },
  { GRASS, TREES, GRASS, TREES, GRASS, GRASS, GRASS, TREES, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS, GRASS },
  { GRASS, TREES, STONE, GRASS, GRASS, GRASS, GRASS, STONE, GRASS, GRASS, GRASS, GRASS, GRASS, STONE, GRASS },
  { GRASS, TREES, GRASS, GRASS, GRASS, GRASS, GRASS, TREES, GRASS, GRASS, GRASS, GRASS, GRASS, WATER, GRASS },
  { GRASS, TREES, GRASS, TREES, GRASS, GRASS, GRASS, WATER, GRASS, GRASS, GRASS, GRASS, GRASS, TREES, GRASS },
  { GRASS, TREES, WATER, TREES, GRASS, GRASS, GRASS, TREES, GRASS, GRASS, GRASS, GRASS, GRASS, TREES, GRASS },
};
